/** Short, plain names for skills, shown in lists. The full technical title stays on the skill page. */
export const PLAIN_TITLE: Record<string, string> = {
  'P.exp-laws': 'Exponent laws',
  'P.radicals': 'Working with radicals',
  'P.factor-basic': 'Factoring basics',
  'P.factor-trinomial': 'Factoring trinomials',
  'P.quad-solve': 'Solving quadratics',
  'P.quad-vertex': 'Vertex form of a parabola',
  'P.func-notation': 'Function notation f(x)',
  'P.domain-range': 'Domain and range',
  'P.linear': 'Lines and slope',
  'P.abs': 'Absolute value',
  'P.rat-expr': 'Rational expressions',
  'P.rat-eq': 'Rational equations',
  'P.rad-eq': 'Radical equations (review)',
  'P.systems': 'Solving systems with graphs',
  'P.ref-angle': 'Angles and reference angles (degrees)',
  'P.sine-cos-law': 'Sine law and cosine law',
  'RF2.translate': 'Sliding a graph (translations)',
  'RF3.stretch-v': 'Vertical stretches',
  'RF3.stretch-h': 'Horizontal stretches',
  'RF5.reflect-axes': 'Reflections in the axes',
  'RF3.invariant': 'Points that do not move (invariant points)',
  'RF4.combined': 'Several transformations at once',
  'RF4.factor-b': 'Factoring out b first',
  'RF4.equation-from-graph': 'Writing the equation from a graph',
  'RF4.domain-range-image': 'Domain and range after a transformation',
  'RF5.reflect-yx': 'Reflecting in the line y = x',
  'RF6.inverse-alg': 'Finding an inverse',
  'RF6.restrict': 'Restricting the domain for an inverse',
  'RF6.params': 'Unknowns from a point on the inverse',
  'RF13.sqrt-transform': 'Transforming y = √x',
  'RF13.sqrt-of-f': 'Graphing y = √f(x)',
  'RF13.solve': 'Solving radical equations',
  'RF12.characteristics': 'Features of a polynomial',
  'RF11.long-division': 'Long division of polynomials',
  'RF11.synthetic': 'Synthetic division',
  'RF11.remainder-thm': 'The remainder theorem',
  'RF11.factor-thm': 'The factor theorem',
  'RF11.integral-zero': 'Possible whole-number zeros',
  'RF11.factor-full': 'Factoring a polynomial fully',
  'RF12.zeros-multiplicity': 'Zeros and how the graph touches or crosses',
  'RF12.sketch': 'Sketching a polynomial',
  'RF12.equation-from-graph': 'Polynomial equation from a graph',
  'RF12.analyze-calc': 'Polynomials on the calculator',
  'RF12.model': 'Polynomial word problems',
  'T1.radians': 'Radians',
  'T1.coterminal': 'Coterminal angles',
  'T1.reference': 'Reference angles',
  'T1.arc-length': 'Arc length',
  'T2.unit-circle-eq': 'Points on the unit circle',
  'T2.special-points': 'Special points on the unit circle',
  'T3.exact-ratios': 'Exact trig values',
  'T3.ratio-from-point': 'Trig ratios from a point',
  'T3.angle-from-ratio': 'Finding the angle from a ratio',
  'T5.first-degree': 'Solving simple trig equations',
  'T5.general': 'All solutions (general solution)',
  'T4.basic-graphs': 'Graphs of sin, cos and tan',
  'T4.parameters': 'Amplitude, period, phase shift, midline',
  'T4.factor-b': 'Factoring b out of a trig graph',
  'T4.sketch': 'Sketching trig graphs',
  'T4.equation-from-graph': 'Trig equation from a graph',
  'T4.model': 'Trig word problems (Ferris wheel, tides)',
  'T5.graphical': 'Solving trig equations on the calculator',
  'T6.identity-vs-equation': 'Identity or equation?',
  'T6.npv': 'Values that are not allowed',
  'T6.simplify': 'Simplifying with identities',
  'T6.exact-sum-double': 'Sum, difference and double-angle values',
  'T6.prove-basic': 'Proving simple identities',
  'T6.prove-advanced': 'Proving harder identities',
  'T5.second-degree': 'Trig equations by factoring',
  'T5.identity-sub': 'Trig equations that need an identity',
  'RF9.exp-graph': 'Exponential graphs',
  'RF9.exp-transform': 'Transforming exponential graphs',
  'RF10.exp-common-base': 'Exponential equations with the same base',
  'RF7.log-def': 'What a logarithm is',
  'RF7.log-eval': 'Working out logs without a calculator',
  'RF9.log-graph': 'Log graphs',
  'RF8.expand': 'Expanding logs',
  'RF8.condense': 'Combining logs into one',
  'RF8.change-base': 'Change of base',
  'RF10.exp-logs': 'Solving exponential equations with logs',
  'RF10.log-eq': 'Solving log equations',
  'RF10.growth-decay': 'Growth and decay problems',
  'RF10.compound-interest': 'Compound interest',
  'RF10.log-scales': 'Log scales (pH, decibels, earthquakes)',
  'RF14.va-vs-hole': 'Asymptotes and holes',
  'RF14.ha-intercepts': 'Horizontal asymptote and intercepts',
  'RF14.domain-range': 'Domain and range of rational functions',
  'RF14.hole-y': 'Where the hole is',
  'RF14.sketch': 'Sketching rational functions',
  'RF14.equation-from-graph': 'Rational equation from a graph',
  'RF14.solve': 'Solving rational equations',
  'RF1.ops-eval': 'Adding and multiplying functions at a point',
  'RF1.ops-graph': 'Combining graphs',
  'RF1.ops-equation': 'Equations of combined functions',
  'RF1.compose-eval': 'Function of a function at a point',
  'RF1.compose-equation': 'Equation of f(g(x))',
  'RF1.decompose': 'Breaking a function into parts',
  'PCBT1.fcp': 'Counting choices (fundamental counting principle)',
  'PCBT1.factorial': 'Factorials',
  'PCBT2.npr': 'Permutations',
  'PCBT2.constraints': 'Arrangements with conditions',
  'PCBT2.repeated': 'Arrangements with repeated items',
  'PCBT2.cases': 'Counting in cases',
  'PCBT2.solve-n': 'Solving for n in permutations',
  'PCBT3.ncr': 'Combinations',
  'PCBT3.at-least': '"At least" and "at most" problems',
  'PCBT3.mixed': 'Permutation or combination?',
  'PCBT3.solve-n': 'Solving for n in combinations',
  'PCBT4.pascal': "Pascal's triangle",
  'PCBT4.expand': 'Expanding (x + y)ⁿ',
  'PCBT4.general-term': 'Finding one term',
  'PCBT4.nonlinear-term': 'Finding a term with powers inside',
  'PCBT4.find-unknown': 'Finding an unknown from a term',
  'CALC.mode-window': 'Calculator: choosing a window',
  'CALC.mode': 'Calculator: degree or radian mode',
  'CALC.intersect-zero': 'Calculator: intersect and zero',
  'CALC.max-min': 'Calculator: maximum and minimum',
  'CALC.table': 'Calculator: tables',
  'EXAM.nr-recording': 'Filling in numerical-response answers',
  'EXAM.directing-words': 'Exam words (explain, justify, prove…)',
  'EXAM.wr-hygiene': 'Avoiding lost marks in written response',
  'EXAM.sketch-standard': 'Sketches that earn full marks',
};
