// Generated from the checked video list. Every id was confirmed with YouTube oEmbed.
import type { LessonVideo } from './videos';

export const VIDEO_DATA: Record<string, LessonVideo> = {
  "P.exp-laws": { id: "5qMEInZslUs", title: "U3L1L2 Review of Exponents and Solving Exponential Equations with a common base", channel: "Aaron Trimble", course: "Math 30-1" },
  "P.radicals": { id: "-QJOBMD5oH4", title: "U2L1 Entire and mixed Radicals", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.factor-basic": { id: "_m81LEgDv6k", title: "U4L1 Review of Factoring", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.factor-trinomial": { id: "EBMPwgF-L6M", title: "U4L2 Factoring Trinomials of the form ax^2 + bx + c", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.quad-solve": { id: "Z8RQYjofePE", title: "U5L6 Roots of Quadratic Equations - The Quadratic Formula", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.quad-vertex": { id: "BntMqxGCL2A", title: "U5L5 Converting From General Form to Standard Form By Completing the Square", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.func-notation": { id: "V1jjoqycYy0", title: "U1L1 Functions Review", channel: "Aaron Trimble", course: "Math 30-1" },
  "P.domain-range": { id: "V1jjoqycYy0", title: "U1L1 Functions Review", channel: "Aaron Trimble", course: "Math 30-1" },
  "P.linear": { id: "8nomqUbzcSA", title: "MATH 10C: Slope-Intercept Form, Slope-Point Form, General Form, Parallel & Perpendicular Lines", channel: "The Auxi Project", course: "other" },
  "P.abs": { id: "xg9JNhK3KCM", title: "U7L1 Absolute Value Functions", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.rat-expr": { id: "KyO44DTPBKM", title: "U6L1 Simplifying Rational Expressions", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.rat-eq": { id: "eFCRABkPgmY", title: "U6L7 Rational Equations Part 1", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.rad-eq": { id: "__3CJWm8_9w", title: "U4L6 Solving Radical Equations Using Factoring Part One", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.systems": { id: "QOQG1IxjbgA", title: "U8L1 Solving a System of Linear Quadratic Equations", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.ref-angle": { id: "nCuNqkBeOk8", title: "U3L1 Rotation Angles and Reference Angles", channel: "Aaron Trimble", course: "Math 20-1" },
  "P.sine-cos-law": { id: "xb3spzvU-gE", title: "U3L8 Further Applications Involving the Sine Law and the Cosine Law", channel: "Aaron Trimble", course: "Math 20-1" },
  "RF2.translate": { id: "fZItvc8SzP0", title: "Pre-Calc 12 Section 1.1", channel: "aleemath", course: "Math 30-1" },
  "RF3.stretch-v": { id: "R0htdSyTeH0", title: "Pre-Calc 12 Section 1.2", channel: "aleemath", course: "Math 30-1" },
  "RF3.stretch-h": { id: "R0htdSyTeH0", title: "Pre-Calc 12 Section 1.2", channel: "aleemath", course: "Math 30-1" },
  "RF5.reflect-axes": { id: "R0htdSyTeH0", title: "Pre-Calc 12 Section 1.2", channel: "aleemath", course: "Math 30-1" },
  "RF3.invariant": { id: "R0htdSyTeH0", title: "Pre-Calc 12 Section 1.2", channel: "aleemath", course: "Math 30-1" },
  "RF4.combined": { id: "Jp2t-J0tcMo", title: "U2L7 Combining Transformations", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF4.factor-b": { id: "iP78blt8qQM", title: "U2L8 Combining Transformations", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF4.equation-from-graph": { id: "iP78blt8qQM", title: "U2L8 Combining Transformations", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF4.domain-range-image": { id: "Jp2t-J0tcMo", title: "U2L7 Combining Transformations", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF5.reflect-yx": { id: "dXBtUNVkpkY", title: "Pre-Calc 12 Section 1.4", channel: "aleemath", course: "Math 30-1" },
  "RF6.inverse-alg": { id: "dXBtUNVkpkY", title: "Pre-Calc 12 Section 1.4", channel: "aleemath", course: "Math 30-1" },
  "RF6.restrict": { id: "dXBtUNVkpkY", title: "Pre-Calc 12 Section 1.4", channel: "aleemath", course: "Math 30-1" },
  "RF6.params": { id: "dXBtUNVkpkY", title: "Pre-Calc 12 Section 1.4", channel: "aleemath", course: "Math 30-1" },
  "RF13.sqrt-transform": { id: "Cu_CTnkHwi0", title: "Pre-Calculus 12 Section 2.1", channel: "aleemath", course: "Math 30-1" },
  "RF13.sqrt-of-f": { id: "8JyK2Cav1bo", title: "Pre-Calculus 12 Section 2.2", channel: "aleemath", course: "Math 30-1" },
  "RF13.solve": { id: "MLjov2q1qb0", title: "Pre-Calculus 12 Section 2.3", channel: "aleemath", course: "Math 30-1" },
  "RF12.characteristics": { id: "zTYaYRardV4", title: "Pre-Calc 12 Section 3.1 part 1", channel: "aleemath", course: "Math 30-1" },
  "RF11.long-division": { id: "qB8yASv_54o", title: "Pre-Calc 12 Section 3.2", channel: "aleemath", course: "Math 30-1" },
  "RF11.synthetic": { id: "qB8yASv_54o", title: "Pre-Calc 12 Section 3.2", channel: "aleemath", course: "Math 30-1" },
  "RF11.remainder-thm": { id: "qB8yASv_54o", title: "Pre-Calc 12 Section 3.2", channel: "aleemath", course: "Math 30-1" },
  "RF11.factor-thm": { id: "zOjviuNYQzg", title: "U5L4 The remainder Theorem and the Factor Theorem", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF11.integral-zero": { id: "4STwU9B-g50", title: "U5L5 Factoring Polynomial Expressions Part 1", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF11.factor-full": { id: "UshvEFRef8M", title: "U5L6 Factoring Polynomial Expressions Part 2", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF12.zeros-multiplicity": { id: "y00Q_XDxSwk", title: "Pre Calc 12 Section 3.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "RF12.sketch": { id: "y00Q_XDxSwk", title: "Pre Calc 12 Section 3.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "RF12.equation-from-graph": { id: "y00Q_XDxSwk", title: "Pre Calc 12 Section 3.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "RF12.analyze-calc": { id: "y00Q_XDxSwk", title: "Pre Calc 12 Section 3.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "RF12.model": { id: "y00Q_XDxSwk", title: "Pre Calc 12 Section 3.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "T1.radians": { id: "Fg5P8-aOs6U", title: "Pre Calc 12 Section 4.1 part 1", channel: "aleemath", course: "Math 30-1" },
  "T1.coterminal": { id: "Fg5P8-aOs6U", title: "Pre Calc 12 Section 4.1 part 1", channel: "aleemath", course: "Math 30-1" },
  "T1.reference": { id: "rKujg0wSGVs", title: "Pre Calc 12 Section 4.1 part 2", channel: "aleemath", course: "Math 30-1" },
  "T1.arc-length": { id: "rKujg0wSGVs", title: "Pre Calc 12 Section 4.1 part 2", channel: "aleemath", course: "Math 30-1" },
  "T2.unit-circle-eq": { id: "UK0M4xFFHso", title: "U8L5 Trigonometric Ratios and the Unit Circle", channel: "Aaron Trimble", course: "Math 30-1" },
  "T2.special-points": { id: "UK0M4xFFHso", title: "U8L5 Trigonometric Ratios and the Unit Circle", channel: "Aaron Trimble", course: "Math 30-1" },
  "T3.exact-ratios": { id: "pl9-91sJoEE", title: "Pre Calc 12 Section 4.3", channel: "aleemath", course: "Math 30-1" },
  "T3.ratio-from-point": { id: "pl9-91sJoEE", title: "Pre Calc 12 Section 4.3", channel: "aleemath", course: "Math 30-1" },
  "T3.angle-from-ratio": { id: "pl9-91sJoEE", title: "Pre Calc 12 Section 4.3", channel: "aleemath", course: "Math 30-1" },
  "T5.first-degree": { id: "PlTdZ4OTWYk", title: "Pre Calc 12 Section 4.4", channel: "aleemath", course: "Math 30-1" },
  "T5.general": { id: "PlTdZ4OTWYk", title: "Pre Calc 12 Section 4.4", channel: "aleemath", course: "Math 30-1" },
  "T4.basic-graphs": { id: "P4rgRJLH05g", title: "Pre-Calc 12 Section 5.1", channel: "aleemath", course: "Math 30-1" },
  "T4.parameters": { id: "5AKepMlZdik", title: "Pre-Calc 12 Section 5.2 part 1", channel: "aleemath", course: "Math 30-1" },
  "T4.factor-b": { id: "nAjfiM9LN6g", title: "Pre-Calc 12 Section 5.2 part 2", channel: "aleemath", course: "Math 30-1" },
  "T4.sketch": { id: "nAjfiM9LN6g", title: "Pre-Calc 12 Section 5.2 part 2", channel: "aleemath", course: "Math 30-1" },
  "T4.equation-from-graph": { id: "Mi3iHEKiGto", title: "Pre-Calc 12 Section 5.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "T4.model": { id: "Mi3iHEKiGto", title: "Pre-Calc 12 Section 5.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "T5.graphical": { id: "Mi3iHEKiGto", title: "Pre-Calc 12 Section 5.4 part 1", channel: "aleemath", course: "Math 30-1" },
  "T6.identity-vs-equation": { id: "iF-Lg94L4rM", title: "Pre-Calc 12 Section 6.1 part 1", channel: "aleemath", course: "Math 30-1" },
  "T6.npv": { id: "iF-Lg94L4rM", title: "Pre-Calc 12 Section 6.1 part 1", channel: "aleemath", course: "Math 30-1" },
  "T6.simplify": { id: "et4pPFoUvB0", title: "Pre-Calc 12 Section 6.1 part 2", channel: "aleemath", course: "Math 30-1" },
  "T6.exact-sum-double": { id: "fsGWbepQNCY", title: "Pre-Calc 12 Section 6.2 part 1", channel: "aleemath", course: "Math 30-1" },
  "T6.prove-basic": { id: "pPmATaRypaY", title: "Pre-Calculus 12 Section 6.3", channel: "aleemath", course: "Math 30-1" },
  "T6.prove-advanced": { id: "pPmATaRypaY", title: "Pre-Calculus 12 Section 6.3", channel: "aleemath", course: "Math 30-1" },
  "T5.second-degree": { id: "56Dlh5UGv7U", title: "Pre-Calcluls 12 Section 6.4", channel: "aleemath", course: "Math 30-1" },
  "T5.identity-sub": { id: "56Dlh5UGv7U", title: "Pre-Calcluls 12 Section 6.4", channel: "aleemath", course: "Math 30-1" },
  "RF9.exp-graph": { id: "M47EuTie_fU", title: "Pre-Calc 12 Section 7.1 part 1", channel: "aleemath", course: "Math 30-1" },
  "RF9.exp-transform": { id: "ABX0R52kJPA", title: "Pre-Calc 12 Section 7.2", channel: "aleemath", course: "Math 30-1" },
  "RF10.exp-common-base": { id: "53qRJX7LCpQ", title: "Pre-Calc 12 Section 7.3", channel: "aleemath", course: "Math 30-1" },
  "RF7.log-def": { id: "iBo-dC9y2Gw", title: "U3L4 Logarithmic Functions", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF7.log-eval": { id: "jquKMK0mcNo", title: "U3L5 Evaluating Logarithms", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF9.log-graph": { id: "l51MsxKAh7k", title: "Pre-Calc 12 Section 8.2", channel: "aleemath", course: "Math 30-1" },
  "RF8.expand": { id: "X7sUdOjQYdU", title: "Pre-Calc 12 Section 8.3 Part 1", channel: "aleemath", course: "Math 30-1" },
  "RF8.condense": { id: "X7sUdOjQYdU", title: "Pre-Calc 12 Section 8.3 Part 1", channel: "aleemath", course: "Math 30-1" },
  "RF8.change-base": { id: "X7sUdOjQYdU", title: "Pre-Calc 12 Section 8.3 Part 1", channel: "aleemath", course: "Math 30-1" },
  "RF10.exp-logs": { id: "a3mtd1Atulg", title: "Pre-Calc 12 Section 8.4 Part 1", channel: "aleemath", course: "Math 30-1" },
  "RF10.log-eq": { id: "a3mtd1Atulg", title: "Pre-Calc 12 Section 8.4 Part 1", channel: "aleemath", course: "Math 30-1" },
  "RF10.growth-decay": { id: "P_8JUKAXqeg", title: "Pre-Calc 12 Section 8.4 Part 2", channel: "aleemath", course: "Math 30-1" },
  "RF10.compound-interest": { id: "P_8JUKAXqeg", title: "Pre-Calc 12 Section 8.4 Part 2", channel: "aleemath", course: "Math 30-1" },
  "RF10.log-scales": { id: "P_8JUKAXqeg", title: "Pre-Calc 12 Section 8.4 Part 2", channel: "aleemath", course: "Math 30-1" },
  "RF14.va-vs-hole": { id: "TGKkFND2t2o", title: "Pre-Calculus 12 Section 9.1", channel: "aleemath", course: "Math 30-1" },
  "RF14.ha-intercepts": { id: "TGKkFND2t2o", title: "Pre-Calculus 12 Section 9.1", channel: "aleemath", course: "Math 30-1" },
  "RF14.domain-range": { id: "DgKQCDWBXzs", title: "U7L5 Graphs of Rational Functions", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF14.hole-y": { id: "zZlyfaHebxM", title: "U7L4 Rational Functions and Points of Dicontinuity", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF14.sketch": { id: "DgKQCDWBXzs", title: "U7L5 Graphs of Rational Functions", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF14.equation-from-graph": { id: "DgKQCDWBXzs", title: "U7L5 Graphs of Rational Functions", channel: "Aaron Trimble", course: "Math 30-1" },
  "RF14.solve": { id: "dhVDNe842U8", title: "Pre-Calculus 12 Section 9.3", channel: "aleemath", course: "Math 30-1" },
  "RF1.ops-eval": { id: "dXbpVBX_q6o", title: "Pre-Calculus 12 Section 10.1", channel: "aleemath", course: "Math 30-1" },
  "RF1.ops-graph": { id: "dXbpVBX_q6o", title: "Pre-Calculus 12 Section 10.1", channel: "aleemath", course: "Math 30-1" },
  "RF1.ops-equation": { id: "X2kjgtQNVL4", title: "Pre-Calculus 12 Section 10.2", channel: "aleemath", course: "Math 30-1" },
  "RF1.compose-eval": { id: "RRUBzOXOkvo", title: "Pre-Calculus 12 Section 10.3", channel: "aleemath", course: "Math 30-1" },
  "RF1.compose-equation": { id: "RRUBzOXOkvo", title: "Pre-Calculus 12 Section 10.3", channel: "aleemath", course: "Math 30-1" },
  "RF1.decompose": { id: "RRUBzOXOkvo", title: "Pre-Calculus 12 Section 10.3", channel: "aleemath", course: "Math 30-1" },
  "PCBT1.fcp": { id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1", channel: "aleemath", course: "Math 30-1" },
  "PCBT1.factorial": { id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1", channel: "aleemath", course: "Math 30-1" },
  "PCBT2.npr": { id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1", channel: "aleemath", course: "Math 30-1" },
  "PCBT2.constraints": { id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1", channel: "aleemath", course: "Math 30-1" },
  "PCBT2.repeated": { id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1", channel: "aleemath", course: "Math 30-1" },
  "PCBT2.cases": { id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1", channel: "aleemath", course: "Math 30-1" },
  "PCBT2.solve-n": { id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1", channel: "aleemath", course: "Math 30-1" },
  "PCBT3.ncr": { id: "rJtH-AVqjVc", title: "Pre-Calculus 12 Section 11.2", channel: "aleemath", course: "Math 30-1" },
  "PCBT3.at-least": { id: "rJtH-AVqjVc", title: "Pre-Calculus 12 Section 11.2", channel: "aleemath", course: "Math 30-1" },
  "PCBT3.mixed": { id: "rJtH-AVqjVc", title: "Pre-Calculus 12 Section 11.2", channel: "aleemath", course: "Math 30-1" },
  "PCBT3.solve-n": { id: "rJtH-AVqjVc", title: "Pre-Calculus 12 Section 11.2", channel: "aleemath", course: "Math 30-1" },
  "PCBT4.pascal": { id: "cRcqfBOaE5k", title: "U6L7 Pascals Triangle", channel: "Aaron Trimble", course: "Math 30-1" },
  "PCBT4.expand": { id: "xwvkq0_hlgE", title: "U6L8 the Binomial Theorem", channel: "Aaron Trimble", course: "Math 30-1" },
  "PCBT4.general-term": { id: "xwvkq0_hlgE", title: "U6L8 the Binomial Theorem", channel: "Aaron Trimble", course: "Math 30-1" },
  "PCBT4.nonlinear-term": { id: "xwvkq0_hlgE", title: "U6L8 the Binomial Theorem", channel: "Aaron Trimble", course: "Math 30-1" },
  "PCBT4.find-unknown": { id: "xwvkq0_hlgE", title: "U6L8 the Binomial Theorem", channel: "Aaron Trimble", course: "Math 30-1" },
  "CALC.mode-window": { id: "Sos6s6EN5AE", title: "Adjusting the Viewing Window and Locating the x-intercepts on a TI-84", channel: "Cole's World of Mathematics", course: "other" },
  "CALC.mode": { id: "9Dg56o6G0MI", title: "Radian vs Degree Mode on your TI-84 Graphing Calculator - tiskills.com", channel: "StraightUpMath", course: "other" },
  "CALC.intersect-zero": { id: "5opcdTCGRgg", title: "How to find Solutions, Minimum, and Maximum on the TI-83/84 Graphing Calculator", channel: "Sharon Serano", course: "other" },
  "CALC.max-min": { id: "5opcdTCGRgg", title: "How to find Solutions, Minimum, and Maximum on the TI-83/84 Graphing Calculator", channel: "Sharon Serano", course: "other" },
  "CALC.table": { id: "aWV267hm4oQ", title: "Using the Table of Values & Setting \"Auto\" or \"Ask\" on the TI-84", channel: "Cole's World of Mathematics", course: "other" },
};

export const SECTION_VIDEO_DATA: Record<string, { id: string; title: string }[]> = {
  "1.1": [{ id: "fZItvc8SzP0", title: "Pre-Calc 12 Section 1.1" }],
  "1.2": [{ id: "R0htdSyTeH0", title: "Pre-Calc 12 Section 1.2" }],
  "1.3": [{ id: "Jp2t-J0tcMo", title: "U2L7 Combining Transformations" }, { id: "iP78blt8qQM", title: "U2L8 Combining Transformations" }],
  "1.4": [{ id: "dXBtUNVkpkY", title: "Pre-Calc 12 Section 1.4" }],
  "2.1": [{ id: "Cu_CTnkHwi0", title: "Pre-Calculus 12 Section 2.1" }],
  "2.2": [{ id: "8JyK2Cav1bo", title: "Pre-Calculus 12 Section 2.2" }],
  "2.3": [{ id: "MLjov2q1qb0", title: "Pre-Calculus 12 Section 2.3" }],
  "3.1": [{ id: "zTYaYRardV4", title: "Pre-Calc 12 Section 3.1 part 1" }],
  "3.2": [{ id: "qB8yASv_54o", title: "Pre-Calc 12 Section 3.2" }],
  "3.3": [{ id: "zOjviuNYQzg", title: "U5L4 The remainder Theorem and the Factor Theorem" }, { id: "4STwU9B-g50", title: "U5L5 Factoring Polynomial Expressions Part 1" }, { id: "UshvEFRef8M", title: "U5L6 Factoring Polynomial Expressions Part 2" }],
  "3.4": [{ id: "y00Q_XDxSwk", title: "Pre Calc 12 Section 3.4 part 1" }],
  "4.1": [{ id: "Fg5P8-aOs6U", title: "Pre Calc 12 Section 4.1 part 1" }, { id: "rKujg0wSGVs", title: "Pre Calc 12 Section 4.1 part 2" }],
  "4.2": [{ id: "UK0M4xFFHso", title: "U8L5 Trigonometric Ratios and the Unit Circle" }],
  "4.3": [{ id: "pl9-91sJoEE", title: "Pre Calc 12 Section 4.3" }],
  "4.4": [{ id: "PlTdZ4OTWYk", title: "Pre Calc 12 Section 4.4" }],
  "5.1": [{ id: "P4rgRJLH05g", title: "Pre-Calc 12 Section 5.1" }],
  "5.2": [{ id: "5AKepMlZdik", title: "Pre-Calc 12 Section 5.2 part 1" }, { id: "nAjfiM9LN6g", title: "Pre-Calc 12 Section 5.2 part 2" }],
  "5.4": [{ id: "Mi3iHEKiGto", title: "Pre-Calc 12 Section 5.4 part 1" }],
  "6.1": [{ id: "iF-Lg94L4rM", title: "Pre-Calc 12 Section 6.1 part 1" }, { id: "et4pPFoUvB0", title: "Pre-Calc 12 Section 6.1 part 2" }],
  "6.2": [{ id: "fsGWbepQNCY", title: "Pre-Calc 12 Section 6.2 part 1" }],
  "6.3": [{ id: "pPmATaRypaY", title: "Pre-Calculus 12 Section 6.3" }],
  "6.4": [{ id: "56Dlh5UGv7U", title: "Pre-Calcluls 12 Section 6.4" }],
  "7.1": [{ id: "M47EuTie_fU", title: "Pre-Calc 12 Section 7.1 part 1" }],
  "7.2": [{ id: "ABX0R52kJPA", title: "Pre-Calc 12 Section 7.2" }],
  "7.3": [{ id: "53qRJX7LCpQ", title: "Pre-Calc 12 Section 7.3" }],
  "8.1": [{ id: "iBo-dC9y2Gw", title: "U3L4 Logarithmic Functions" }, { id: "jquKMK0mcNo", title: "U3L5 Evaluating Logarithms" }],
  "8.2": [{ id: "l51MsxKAh7k", title: "Pre-Calc 12 Section 8.2" }],
  "8.3": [{ id: "X7sUdOjQYdU", title: "Pre-Calc 12 Section 8.3 Part 1" }],
  "8.4": [{ id: "a3mtd1Atulg", title: "Pre-Calc 12 Section 8.4 Part 1" }, { id: "P_8JUKAXqeg", title: "Pre-Calc 12 Section 8.4 Part 2" }],
  "9.1": [{ id: "TGKkFND2t2o", title: "Pre-Calculus 12 Section 9.1" }],
  "9.2": [{ id: "DgKQCDWBXzs", title: "U7L5 Graphs of Rational Functions" }, { id: "zZlyfaHebxM", title: "U7L4 Rational Functions and Points of Dicontinuity" }],
  "9.3": [{ id: "dhVDNe842U8", title: "Pre-Calculus 12 Section 9.3" }],
  "10.1": [{ id: "dXbpVBX_q6o", title: "Pre-Calculus 12 Section 10.1" }],
  "10.2": [{ id: "X2kjgtQNVL4", title: "Pre-Calculus 12 Section 10.2" }],
  "10.3": [{ id: "RRUBzOXOkvo", title: "Pre-Calculus 12 Section 10.3" }],
  "11.1": [{ id: "W8A1c6iRidM", title: "Pre-Calculus 12 Section 11.1 Part 1" }],
  "11.2": [{ id: "rJtH-AVqjVc", title: "Pre-Calculus 12 Section 11.2" }],
  "11.3": [{ id: "cRcqfBOaE5k", title: "U6L7 Pascals Triangle" }, { id: "xwvkq0_hlgE", title: "U6L8 the Binomial Theorem" }],
};

export const SECTION_ORDER_DATA: Record<string, string[]> = {
  "1.1": ["RF2.translate"],
  "1.2": ["RF3.stretch-v", "RF3.stretch-h", "RF5.reflect-axes", "RF3.invariant"],
  "1.3": ["RF4.combined", "RF4.factor-b", "RF4.equation-from-graph", "RF4.domain-range-image"],
  "1.4": ["RF5.reflect-yx", "RF6.inverse-alg", "RF6.restrict", "RF6.params"],
  "2.1": ["RF13.sqrt-transform"],
  "2.2": ["RF13.sqrt-of-f"],
  "2.3": ["RF13.solve"],
  "3.1": ["RF12.characteristics"],
  "3.2": ["RF11.long-division", "RF11.synthetic", "RF11.remainder-thm"],
  "3.3": ["RF11.factor-thm", "RF11.integral-zero", "RF11.factor-full"],
  "3.4": ["RF12.zeros-multiplicity", "RF12.sketch", "RF12.equation-from-graph", "RF12.analyze-calc", "RF12.model"],
  "4.1": ["T1.radians", "T1.coterminal", "T1.reference", "T1.arc-length"],
  "4.2": ["T2.unit-circle-eq", "T2.special-points"],
  "4.3": ["T3.exact-ratios", "T3.ratio-from-point", "T3.angle-from-ratio"],
  "4.4": ["T5.first-degree", "T5.general"],
  "5.1": ["T4.basic-graphs"],
  "5.2": ["T4.parameters", "T4.factor-b", "T4.sketch"],
  "5.4": ["T4.equation-from-graph", "T4.model", "T5.graphical"],
  "6.1": ["T6.identity-vs-equation", "T6.npv", "T6.simplify"],
  "6.2": ["T6.exact-sum-double"],
  "6.3": ["T6.prove-basic", "T6.prove-advanced"],
  "6.4": ["T5.second-degree", "T5.identity-sub"],
  "7.1": ["RF9.exp-graph"],
  "7.2": ["RF9.exp-transform"],
  "7.3": ["RF10.exp-common-base"],
  "8.1": ["RF7.log-def", "RF7.log-eval"],
  "8.2": ["RF9.log-graph"],
  "8.3": ["RF8.expand", "RF8.condense", "RF8.change-base"],
  "8.4": ["RF10.exp-logs", "RF10.log-eq", "RF10.growth-decay", "RF10.compound-interest", "RF10.log-scales"],
  "9.1": ["RF14.va-vs-hole", "RF14.ha-intercepts"],
  "9.2": ["RF14.domain-range", "RF14.hole-y", "RF14.sketch", "RF14.equation-from-graph"],
  "9.3": ["RF14.solve"],
  "10.1": ["RF1.ops-eval", "RF1.ops-graph"],
  "10.2": ["RF1.ops-equation"],
  "10.3": ["RF1.compose-eval", "RF1.compose-equation", "RF1.decompose"],
  "11.1": ["PCBT1.fcp", "PCBT1.factorial", "PCBT2.npr", "PCBT2.constraints", "PCBT2.repeated", "PCBT2.cases", "PCBT2.solve-n"],
  "11.2": ["PCBT3.ncr", "PCBT3.at-least", "PCBT3.mixed", "PCBT3.solve-n"],
  "11.3": ["PCBT4.pascal", "PCBT4.expand", "PCBT4.general-term", "PCBT4.nonlinear-term", "PCBT4.find-unknown"],
};
